name: "Code Style Formatter"

# Uses the black code formatter to reformat just the changed files
#   https://github.com/psf/black

# For finding just the changed files:
#   https://github.community/t/can-i-process-only-changed-files-with-github-actions/137814

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'   # only when at least one python file is included in the commit
  workflow_dispatch:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # No shallow clone, we need all history!

    - name: Find changed files
      run: |
        echo 'CHANGED_FILES<<EOF' >>$GITHUB_ENV
        git diff ${{ github.event.before == '0000000000000000000000000000000000000000' && '4b825dc642cb6eb9a060e54bf8d69288fbee4904' || github.event.before }}..${{ github.event.after }} --name-only '*.py' >> $GITHUB_ENV
        echo 'EOF' >>$GITHUB_ENV

    - name: Show changed files
      run: |
        echo "Changed Files:"
        echo "${CHANGED_FILES}"
        echo "---"

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Black
      run: pip install black

    - name: Run black --check $CHANGED_FILES
      continue-on-error: true
      run: black --check $CHANGED_FILES

    - name: If needed, commit black changes to the pull request
      if: failure()
      run: |
        black $CHANGED_FILES
        git config --global user.name 'code-style'
        git config --global user.email 'royw@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "fixup: Format Python code with Black"
        git push
