# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install flake8 pytest pytest-cov
        python -m pip install build
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        mkdir -p public
        # stop the build if there are Python syntax errors or undefined names
        flake8 versio --count --select=E9,F63,F7,F82 --show-source --statistics --output-file public/syntax-errors.txt
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 versio --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics \
        --output-file public/problems.txt
    - name: Test with pytest
      run: |
        pytest --doctest-modules --junitxml=public/test-results-${{ matrix.python-version }}.xml --cov=versio \
        --cov-report=xml:public/coverage.xml --cov-report=html:public/html-coverage
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: public/test-results-${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Upload pytest coverage XML results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.python-version }}
        path: public/coverage.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Upload pytest coverage HTML report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.python-version }}
        path: public/html-coverage/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Build package
      run: python -m build
    - name: Upload built package
      uses: actions/upload-artifact@v2
      with:
        name: Version-Package-${{ matrix.python-version }}
        path: dist/Versio-*.tar.gz
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Publish reports to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        enable_jekyll: true
    # Use always() to always run this step to publish test results when there are test failures
    if: ${{ always() }}
